export const USER_PROFILE = 'USER_PROFILE';

export const GET_PUBLISHERS_REQUEST = 'GET_PUBLISHERS_REQUEST';
export const GET_PUBLISHERS_SUCCESS = 'GET_PUBLISHERS_SUCCESS';
export const GET_PUBLISHERS_FAILURE = 'GET_PUBLISHERS_FAILURE';
