export const USER_PROFILE = 'USER_PROFILE';
export const URL = 'http://localhost:8888/ms/rest';

export const GET_PUBLISHERS_REQUEST = 'GET_PUBLISHERS_REQUEST';
export const GET_PUBLISHERS_SUCCESS = 'GET_PUBLISHERS_SUCCESS';
export const GET_PUBLISHERS_FAILURE = 'GET_PUBLISHERS_FAILURE';

export const ADD_PUBLISHER_REQUEST = 'ADD_PUBLISHER_REQUEST';
export const ADD_PUBLISHER_SUCCESS = 'ADD_PUBLISHER_SUCCESS';
export const ADD_PUBLISHER_FAILURE = 'ADD_PUBLISHER_FAILURE';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'ADD_USER_FAILURE';
