let TodoConstants = {
    ADD_TODO_REQUEST: 'ADD_TODO_REQUEST',
    ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
    ADD_TODO_FAILURE: 'ADD_TODO_FAILURE',
    UPDATE_TODO_REQUEST: 'UPDATE_TODO_REQUEST',
    UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
    UPDATE_TODO_FAILURE: 'UPDATE_TODO_FAILURE',
    REMOVE_TODO_REQUEST: 'REMOVE_TODO_REQUEST',
    REMOVE_TODO_SUCCESS: 'REMOVE_TODO_SUCCESS',
    REMOVE_TODO_FAILURE: 'REMOVE_TODO_FAILURE',
    GET_TODOS_REQUEST: 'GET_TODOS_REQUEST',
    GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
    GET_TODOS_FAILURE: 'GET_TODOS_FAILURE'
};

export default TodoConstants;
